<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jobilla/appevents/options.proto

namespace Jobilla\Protobuf\AppEvents\Metadata;

class Options
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‚
jobilla/appevents/options.protojobilla.appevents google/protobuf/descriptor.protoBÅZ<github.com/jobilla/protoc-gen-go-appevents/jobilla/appevents Jobilla\\Protobuf\\AppEvents‚#Jobilla\\Protobuf\\AppEvents\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

